version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dupword
    - godot
    - err113
    - exhaustruct
    - forcetypeassert
    - godox
    - ireturn
    - lll
    - modernize
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - promlinter
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    funlen:
      lines: 120
      statements: 60
    gosec:
      excludes:
      - 'G115'
    gocritic:
      disabled-checks:
        - emptyStringTest
        - httpNoBody
        - octalLiteral
        - importShadow
        - elseif
        - ifElseChain
        - unnamedResult
        - unnecessaryDefer
        - whyNoLint
        - commentFormatting
      enabled-tags:
        - performance
        - style
        - diagnostic
#    revive: # Dnx: let's try
#      rules:
#        - name: unused-parameter
#          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test.go
        linters:
          - dupl
          - funlen
          - gocognit
          - gocritic
          - gosec
          - maintidx
          - mnd
          - noctx
          - testpackage
          - thelper
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
#  settings:
#    goimports:
#      local-prefixes:
#        - apim-mcp-gw
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
